
server:
  port: 8083
  servlet:
    context-path: /cookingapp
spring:
  application:
    name: CookingApp
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: cooking
    password: abcd1234
  jpa:
    properties:
      hibernate:

    hibernate:
      ddl-auto: update
    show-sql: true

project:
  foodimage: foodimage/


base:
  url: "http://localhost:8083"

jwt:
  signerKey: "hlPp9x4GIOQVHBewHlAtg2PJtw98OFrY0IOmYv4EC9zpmU5sUcqBtP2rW+gsJ2vX"
  valid-duration: 3600 #in second #het han sau
  refreshable-duration: 120 #second #token moi co thoi han
