name: tutorial
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  fluttertoast: ^8.2.8
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.3.2
  lottie: ^3.1.2
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

